---
 - name: create a RoboShop 
   hosts: 172.31.33.200
   become: true
   tasks:
    - name: Copy user.service file to /etc/systemd/system/
      ansible.builtin.template:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: set prompt
      ansible.builtin.command: set-prompt cart
      
    - name: Disable existing Node.js module
      command: dnf module disable nodejs -y
    
    - name: Enable Node.js 20 module
      command: dnf module enable nodejs:20 -y

    - name: Install Node.js
      dnf:
        name: nodejs
        state: present

    - name: Add application user 'roboshop'
      user:
        name: roboshop
        system: yes
        shell: /sbin/nologin
        create_home: no

    - name: Create application directory
      file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop
        mode: '0755'

    - name: Download Cart microservice application code
      get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

    - name: Extract application code
      unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: /app

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: download the cart content
      ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
       dest: /tmp/cart.zip
    - name: extract
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes  
    - name: download the npm
      ansible.builtin.dnf:
        name: npm
        state: installed

    - name: Reload systemd daemon
      ansible.builtin.command: systemctl daemon-reload

    - name: start and enable cart
      ansible.builtin.service:
        name: cart.service
        state: restarted
        enabled: yes
