- name: hosts
  hosts: 172.31.33.200
  become : true
  tasks:

    - name: start and enable cart
      ansible.builtin.service:
        name: cart.service
        state: restarted
        enabled: yes

