---
 - name: create the roboshop
   hosts: 172.31.40.150
   become: true
   tasks:
     - name: set prompt
       ansible.builtin.shell: set-prompt catalogue
     
     - name: disable the nodejs 
       ansible.builtin.command:  dnf module disable nodejs -y
 

     - name: enable the nodejs 
       ansible.builtin.command: dnf module enable nodejs:20 -y


     - name: install the catalogue
       ansible.builtin.dnf:
         name: nodejs
         state: installed
     - name: add the user with roboshop
       ansible.builtin.user:
         name: roboshop
         state: present
      
     - name: Creates directory
       ansible.builtin.file:
         path: /app
         state: directory
        
     - name: download the catalogure content
       ansible.builtin.get_url:
         url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
         dest: /tmp/catalogue.zip
     - name: extract the catalogue 
       ansible.builtin.unarchive:
         src: /tmp/catalogue.zip
         dest: /app
         remote_src: yes  
     - name: download the npm
       ansible.builtin.dnf:
         name: npm
         state: installed
      
     - name: Copy file with owner and permissions
       ansible.builtin.copy:
         src: catalogue.service
         dest: /etc/systemd/system
      
     - name: reload the daemon-reload
       ansible.builtin.command: systemctl daemon-reload
      
     - name: start and enable catalogue
       ansible.builtin.systemd_service:
         name: catalogue
         state: started
         enabled: yes
