---
- name: create a RoboShop Dispatch
  hosts: dispatch
  become: true
  tasks:
    - name: set prompt
      ansible.buildin.command: set-prompt shipping

    - name: Install GoLang
      dnf:
        name: golang
        state: present

    - name: Add application user 'roboshop'
      user:
        name: roboshop
        system: yes
        shell: /sbin/nologin
        create_home: no

    - name: Create application directory
      file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop
        mode: '0755'

    - name: Download Dispatch microservice application code
      get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
        dest: /tmp/dispatch.zip

    - name: Extract application code
      unarchive:
        src: /tmp/dispatch.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Initialize Go module
      command: go mod init dispatch
      args:
        chdir: /app

    - name: Get Go dependencies
      command: go get
      args:
        chdir: /app

    - name: Build Dispatch Go application
      command: go build
      args:
        chdir: /app

    - name: Download the dispatch content
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
        dest: /tmp/dispatch.zip
        mode: '0644'

    - name: Extract dispatch content
      ansible.builtin.unarchive:
        src: /tmp/dispatch.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Copy systemd service file
      ansible.builtin.copy:
        src: dispatch.service
        dest: /etc/systemd/system/dispatch.service
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start dispatch service
      ansible.builtin.systemd:
        name: dispatch
        enabled: yes
        state: started
