---
- name: create a Frontend
  hosts: frontend
  become: true
  
  tasks:
    - name: Disable existing Nginx module
      command: dnf module disable nginx -y
    
    - name: Enable Nginx 1.24 module
      command: dnf module enable nginx:1.24 -y

    - name: Install Nginx
      dnf:
        name: nginx
        state: present
      
    - name: start and enable nginx
      ansible.buildin.dnf:
        name: nginx
        state: started
        enabled: yes
     
    - name: remove the content of nginx
      file:
        path: rm -rf /usr/share/nginx/html/*
        state: absent

    - name: download the frontend content
      ansible.buildin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend.zip

    - name: extract the frontend
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
      
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: nginx.conf
        dest: /usr/share/nginx/html
 
    - name: Restart Nginx
      ansible.buildin.service:
       name: nginx
       state: restarted       



