---
 - name: create a RoboShop
   hosts: 172.31.40.120
   become: true
   tasks:
    - name: set prompt
      ansible.builtin.command: set-prompt mysql
      
    - name: Install MySQL Server
      dnf:
        name: mysql-server
        state: present

    - name: Enable and Start MySQL Service
      systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: Set MySQL root password
      command: "mysql_secure_installation --set-root-pass RoboShop@1"

      
