---
 - name: create the roboshop
   hosts:  payment
   become: true
   tasks:
     - name: install the package
       ansible.buildin.dnf:
        name: python3 gcc python3-devel -y
        state: present
   
     - name: add the user with roboshop
       ansible.buildin.user:
         name: roboshop
         state: present
  
     - name: Creates directory
       ansible.builtin.file:
         path: /app
         state: present

     - name: download the catalogure content
       ansible.buildin.get_url:
         url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
         dest: /tmp/payment.zip

     - name: Install pip and dependencies
       ansible.buildin.dnf:  
         name: python3-pip
         state: present
        

     - name: Install requirements
       ansible.buildin.dnf:  
         requirements: /app/requirements.txt
         executable: pip3   

     - name: reload the daemon-reload
       ansible.buildin.service:
         name: daemon-reload
         state: reload
      
     - name: start and enable cart
       ansible.buildin.dnf:
         name: payment
         state: started
         enabled: yes
    
