---
 - name: create a RoboShop
   hosts: user
   become: true
   tasks:
    - name: set prompt
      ansible.buildin.command: set-prompt user
      
    - name: Disable existing Node.js module
      command: dnf module disable nodejs -y
    
    - name: Enable Node.js 20 module
      command: dnf module enable nodejs:20 -y

    - name: Install Node.js
      dnf:
        name: nodejs
        state: present

    - name: Add application user 'roboshop'
      user:
        name: roboshop
        system: yes
        shell: /sbin/nologin
        create_home: no

    - name: Create application directory
      file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop
        mode: '0755'

    - name: Download User microservice application code
      get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip

    - name: Extract application code
      unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: /app

    - name: Set ownership and permissions for /app directory
      file:
        path: /app
        state: directory

    - name: download the catalogure content
      ansible.buildin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
       dest: /tmp/user.zip
      
    - name: download the npm
      ansible.buildin.dnf:
       name: npm
       state: installed
      
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
       src: user.service
       dest: /etc/systemd/system
      
    - name: reload the daemon-reload
      ansible.buildin.service:
       name: daemon-reload
      state: reload
      
    - name: start and enable user
      ansible.buildin.dnf:
       name: user
       state: started
       enabled: yes
      