---
 - name: create a RoboShop
   hosts: 172.31.38.215
   become: true
   tasks:
    - name: set prompt
      ansible.builtin.command: set-prompt user
      
    - name: Disable existing Node.js module
      command: dnf module disable nodejs -y
    
    - name: Enable Node.js 20 module
      command: dnf module enable nodejs:20 -y

    - name: Install Node.js
      dnf:
        name: nodejs
        state: installed

    - name: Add application user 'roboshop'
      user:
        name: roboshop
        system: yes
        shell: /sbin/nologin
        create_home: no

    - name: Create application directory
      file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop
        mode: '0755'

    - name: Download User microservice application code
      get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip

    - name: Extract application code
      unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: /app

    - name: Set ownership and permissions for /app directory
      file:
        path: /app
        state: directory

    - name: download the catalogure content
      ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
       dest: /tmp/user.zip
      
    - name: Extract application code
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes  
     
    - name: download the npm
      ansible.builtin.dnf:
        name: npm
        state: installed
      
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system
      
    - name: reload the daemon-reload
      ansible.builtin.command: systemctl daemon-reload

      
    - name: start and enable user
      ansible.builtin.systemd_service:
        name: user
        state: started
        enabled: yes
      
